<a href="https://colab.research.google.com/github/shreyashganvir77/Learn.MachineLearning.python/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the libraries.

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset.

In [6]:
#pandas library is used to read the csv file.
#the data read is stored as a data frame, which can be accessed as the row and column matrix, with iloc fuction.
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[ :, :-1].values
y = dataset.iloc[ :, -1].values
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Handling the missing data.

In [7]:
#the missing values can be replaces with average of column.
#or using mean and median also.
#sklearn library

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Encoding Categorical Data.

In [8]:
#In encodings use the oneHotEncoding method which converts the repeating strings in the column into binary values.
#For example France is encoded as 100, spain as 001 and germany as 010.

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#the transformer accepts a tuple of three of encoder, which type of encoding (i.e OneHotEncoder)
#and then remaining rows should not be affected that's why we use remainder and passthrough
#these two arguments are neccessary in the columnTransformer class.
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encoding for the Dependent Data.

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


Splitting the data into Training set and Test set.

In [10]:
  #the sklearn sklearn model_selection module is used to split the datasets into model training and test sets.
#we can provide the percentage of train and test dataset by test_size argument in train_test_split.

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 1)

In [ ]:
print(x_train)  

In [16]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(x_test)

In [ ]:
print(y_test)

Feature Scaling.

In [17]:
# The feature scaling is applied after the datasets are divided into train and test.
# This is important to avoid data leakage, the futture data on which model will be runned,
# should not know the early feature scaling or data.

# Feature Scaling
# standardisation(all time applicable) and normaliastion(if data is normalised)

from sklearn import preprocessing
sc = preprocessing.StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])  
